name: Publish Open VSX

on:
  push:
    tags:
      - "ovsx-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-extension

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run compile

      - run: npx @vscode/vsce package --no-update-package-json

      - run: npx ovsx publish *.vsix -p ${{ secrets.OVSX_PAT }}
