name: Publish VS Code Extension

on:
  push:
    tags:
      - "vscode-v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vscode-extension

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npm run compile

      - run: npx @vscode/vsce publish --no-update-package-json
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - run: npx ovsx publish --no-update-package-json -p ${{ secrets.OVSX_PAT }}
